#Name of the workflow
name: Release

# Run on every commit tag which begins with "v" (e.g. "v0.1.4")
on:
  push:
    tags:
      - "v*"


#Automatically create a GitHub Release, with relesase details specified (the relevant commits)
jobs:

  runs-on:ubuntu-latest
  permissions:
    contents: read
    packages: write

  steps:
      - uses: "actions/action-automatic-releases@latest"
        - name: Set up JDK 17
            uses: actions/setup-java@v2
  with:
    repo_token: "${{ secrets.GITHUB_TOKEN}}"
    prerelease: false
    java-version: '17'
    distribution: 'temurin'
    server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
    settings-path: ${{ github.workspace }} # location for the settings.xml file


      - name: Build with Maven
        run: mvn -B package --file pom.xml

      - name: Publish to GitHub Packages Apache Maven
        run: mvn deploy -s $GITHUB_WORKSPACE/settings.xml
        env:
          GITHUB_TOKEN: ${{ github.token }}


